{% set name = "spectra-cpp" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: spectra-{{ version }}.tar.gz
  url: https://github.com/yixuan/spectra/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 919e3fbc8c539a321fd5a0766966922b7637cc52eb50a969241a997c733789f3

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('spectra-cpp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
    - eigen
  run: []

test:
  commands:
    - test -d ${PREFIX}/include/Spectra  # [unix]
    - test -d ${PREFIX}/share/spectra/cmake  # [unix]
    - test -f ${PREFIX}/include/Spectra/GenEigsBase.h  # [unix]
    - test -f ${PREFIX}/share/spectra/cmake/spectra-config.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\Spectra\GenEigsBase.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\share\spectra\cmake\spectra-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/yixuan/spectra
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: A header-only C++ library for large scale eigenvalue problems
  description: A header-only C++ library for large scale eigenvalue problems
  doc_url: https://github.com/yixuan/spectra
  dev_url: https://github.com/yixuan/spectra

extra:
  recipe-maintainers:
    - timkpaine
